# Generated by Django 5.1.3 on 2024-12-07 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0004_alter_library_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='library',
            options={},
        ),
    ]
